### ISSUE TITLE
How to Connnect to Sysinternals Server

### ISSUE THREAD

**Issue by Meinfield** [Snap-for-Windows/snap-plugin-collector-sysinternals#7]
The title ^

**Comment by KadeTheKade** [comment]
http://www.howtogeek.com/school/sysinternals-pro/lesson1/

Running the sysinternals tools from the fileshare is simple, but when I tried it, incredibly slow. This could work, but it might be better to figure out how to install the tools locally via a powershell script.

**Comment by KadeTheKade** [comment]
https://gallery.technet.microsoft.com/scriptcenter/Another-Sysinternals-Tools-aa288439

Here is a powershell script for automatically downloading the sysinternals suite.

**Comment by Meinfield** [comment]
Research for this is done
